/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dev.senzalla.auxiliarcodeformater;

import dev.senzalla.auxiliarcodeformater.service.FileNode;
import dev.senzalla.auxiliarcodeformater.service.FileSpring;

import javax.swing.*;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Set;

/**
 * @author Bomsalvez
 */
public class AuxiliarCodeFormaterApplication extends javax.swing.JFrame {

    /**
     * Creates new form AuxiliarCodeFormaterApplication
     */
    public AuxiliarCodeFormaterApplication() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chooserPathProject = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        checkController = new javax.swing.JCheckBox();
        checkService = new javax.swing.JCheckBox();
        checkRepository = new javax.swing.JCheckBox();
        checkSettings = new javax.swing.JCheckBox();
        checkProperties = new javax.swing.JCheckBox();
        checkModel = new javax.swing.JCheckBox();
        txtFilePath = new javax.swing.JTextField();
        btnChooseFile = new javax.swing.JButton();
        btnCreateDiretories = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();
        btnClean = new javax.swing.JButton();

        chooserPathProject.setCurrentDirectory(new File(System.getProperty("user.home")));
        chooserPathProject.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Criador de Arquivos e Diretorios");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel1.setOpaque(true);

        checkController.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        checkController.setSelected(true);
        checkController.setText("Controller");

        checkService.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        checkService.setSelected(true);
        checkService.setText("Service");

        checkRepository.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        checkRepository.setSelected(true);
        checkRepository.setText("Repository");

        checkSettings.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        checkSettings.setSelected(true);
        checkSettings.setText("Settings");

        checkProperties.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        checkProperties.setText("Properties");

        checkModel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        checkModel.setSelected(true);
        checkModel.setText("Model");

        txtFilePath.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtFilePath.addCaretListener(this::txtFilePathCaretUpdate);

        btnChooseFile.setText("jButton1");
        btnChooseFile.addActionListener(this::btnChooseFileActionPerformed);

        btnCreateDiretories.setBackground(new java.awt.Color(0, 204, 51));
        btnCreateDiretories.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        btnCreateDiretories.setText("Converter");
        btnCreateDiretories.addActionListener(evt -> {
            SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
                @Override
                protected Void doInBackground() throws Exception {
                    Path pathPom = returnPathPom();
                    File file = chooserPathProject.getSelectedFile() != null ? chooserPathProject.getSelectedFile() : new File(txtFilePath.getText());
                    Set<JCheckBox> boxes = Set.of(checkModel, checkRepository, checkService, checkController, checkSettings, checkProperties);
                    if (Files.exists(pathPom)) {
                        new FileSpring().creteFilesSpring(file, boxes);
                    } else {
                        new FileNode().createFilesNode(file, boxes);
                    }
                    return null;
                }

                @Override
                protected void done() {
                    btnCreateDiretories.setEnabled(true);
                    progressBar.setValue(100);
                    progressBar.setString("Concluído!");
                }
            };

            btnCreateDiretories.setEnabled(false);
            worker.execute();
        });

        btnClean.setBackground(new java.awt.Color(255, 0, 51));
        btnClean.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        btnClean.setText("Limpar");
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(113, 113, 113)
                                                .addComponent(checkController)
                                                .addGap(18, 18, 18)
                                                .addComponent(checkService)
                                                .addGap(18, 18, 18)
                                                .addComponent(checkRepository)
                                                .addGap(18, 18, 18)
                                                .addComponent(checkSettings)
                                                .addGap(18, 18, 18)
                                                .addComponent(checkModel)
                                                .addGap(18, 18, 18)
                                                .addComponent(checkProperties))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(57, 57, 57)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                .addComponent(txtFilePath)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btnChooseFile, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(btnCreateDiretories, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btnClean, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)))))
                                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(checkController)
                                        .addComponent(checkService)
                                        .addComponent(checkRepository)
                                        .addComponent(checkSettings)
                                        .addComponent(checkModel)
                                        .addComponent(checkProperties))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnChooseFile, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnClean, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnCreateDiretories, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void txtFilePathCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtFilePathCaretUpdate
        Path pathPom = returnPathPom();
        checkProperties.setSelected(Files.exists(pathPom));
        checkProperties.setVisible(Files.exists(pathPom));
    }//GEN-LAST:event_txtFilePathCaretUpdate

    private void btnChooseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseFileActionPerformed
        int optionChooser = chooserPathProject.showDialog(this, "OK");
        if (optionChooser == JFileChooser.APPROVE_OPTION) {
            txtFilePath.setText(String.valueOf(chooserPathProject.getSelectedFile()));
        }
    }//GEN-LAST:event_btnChooseFileActionPerformed


    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        txtFilePath.setText(null);
        chooserPathProject.setCurrentDirectory(null);
        progressBar.setValue(0);
    }//GEN-LAST:event_btnCleanActionPerformed

    private Path returnPathPom() {
        String pathProject = String.format("%s/pom.xml", txtFilePath.getText());
        File file = new File(pathProject);
        if (file.exists()) {
            return file.toPath();
        } else {
            return new File(txtFilePath.getText()).toPath();
        }
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuxiliarCodeFormaterApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuxiliarCodeFormaterApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuxiliarCodeFormaterApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuxiliarCodeFormaterApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AuxiliarCodeFormaterApplication().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChooseFile;
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnCreateDiretories;
    private javax.swing.JCheckBox checkController;
    private javax.swing.JCheckBox checkModel;
    private javax.swing.JCheckBox checkProperties;
    private javax.swing.JCheckBox checkRepository;
    private javax.swing.JCheckBox checkService;
    private javax.swing.JCheckBox checkSettings;
    private javax.swing.JFileChooser chooserPathProject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JTextField txtFilePath;
    // End of variables declaration//GEN-END:variables
}
